// Rust implementation of the local:github component.
//
// Makes GitHub API calls via raw wasi:http/outgoing-handler bindings
// generated by wit-bindgen 0.57.1. Authentication is per-call via an
// optional bearer token.

use serde::Deserialize;

wit_bindgen::generate!({
    world: "github",
    path: "wit",
    generate_all,
});

use exports::local::github::api::{Guest, RepoInfo, UserInfo};
use wasi::http::outgoing_handler;
use wasi::http::types::{
    Fields, Method, OutgoingRequest, RequestOptions, Scheme,
};
use wasi::io::streams::StreamError;

const USER_AGENT: &str = "github-wasm-rs/0.1";

#[derive(Deserialize)]
struct GhUser {
    login: String,
    id: u64,
    name: Option<String>,
    bio: Option<String>,
    public_repos: u32,
    followers: u32,
    following: u32,
    html_url: String,
}

#[derive(Deserialize)]
struct GhRepo {
    full_name: String,
    description: Option<String>,
    stargazers_count: u32,
    forks_count: u32,
    language: Option<String>,
    default_branch: String,
    html_url: String,
}

fn http_get_json(path: &str, token: Option<&str>) -> Result<Vec<u8>, String> {
    let headers = Fields::new();
    headers
        .append(&"User-Agent".to_string(), &USER_AGENT.as_bytes().to_vec())
        .map_err(|e| format!("header: {e:?}"))?;
    headers
        .append(
            &"Accept".to_string(),
            &b"application/vnd.github+json".to_vec(),
        )
        .map_err(|e| format!("header: {e:?}"))?;
    if let Some(t) = token {
        let v = format!("Bearer {t}").into_bytes();
        headers
            .append(&"Authorization".to_string(), &v)
            .map_err(|e| format!("header: {e:?}"))?;
    }

    let req = OutgoingRequest::new(headers);
    req.set_method(&Method::Get).map_err(|_| "set method")?;
    req.set_scheme(Some(&Scheme::Https))
        .map_err(|_| "set scheme")?;
    req.set_authority(Some("api.github.com"))
        .map_err(|_| "set authority")?;
    req.set_path_with_query(Some(path))
        .map_err(|_| "set path")?;

    let opts = RequestOptions::new();
    let _ = opts.set_connect_timeout(Some(10_000_000_000));
    let _ = opts.set_first_byte_timeout(Some(10_000_000_000));

    let future = outgoing_handler::handle(req, Some(opts))
        .map_err(|e| format!("handle: {e:?}"))?;

    let resp = loop {
        match future.get() {
            Some(r) => break r.map_err(|_| "future already taken")?.map_err(|e| format!("{e:?}"))?,
            None => future.subscribe().block(),
        }
    };

    let status = resp.status();
    let body = resp.consume().map_err(|_| "consume body")?;

    let bytes = {
        let stream = body.stream().map_err(|_| "body stream")?;
        let mut buf = Vec::new();
        loop {
            match stream.read(64 * 1024) {
                Ok(chunk) if chunk.is_empty() => stream.subscribe().block(),
                Ok(chunk) => buf.extend_from_slice(&chunk),
                Err(StreamError::Closed) => break,
                Err(e) => return Err(format!("read: {e:?}")),
            }
        }
        buf
    };

    if !(200..300).contains(&status) {
        let snippet = String::from_utf8_lossy(&bytes);
        return Err(format!("HTTP {status}: {snippet}"));
    }
    Ok(bytes)
}

struct Component;

impl Guest for Component {
    fn get_user(login: String, token: Option<String>) -> Result<UserInfo, String> {
        let path = format!("/users/{login}");
        let bytes = http_get_json(&path, token.as_deref())?;
        let u: GhUser =
            serde_json::from_slice(&bytes).map_err(|e| format!("parse: {e}"))?;
        Ok(UserInfo {
            login: u.login,
            id: u.id,
            name: u.name,
            bio: u.bio,
            public_repos: u.public_repos,
            followers: u.followers,
            following: u.following,
            html_url: u.html_url,
        })
    }

    fn get_repo(
        owner: String,
        repo: String,
        token: Option<String>,
    ) -> Result<RepoInfo, String> {
        let path = format!("/repos/{owner}/{repo}");
        let bytes = http_get_json(&path, token.as_deref())?;
        let r: GhRepo =
            serde_json::from_slice(&bytes).map_err(|e| format!("parse: {e}"))?;
        Ok(RepoInfo {
            full_name: r.full_name,
            description: r.description,
            stargazers_count: r.stargazers_count,
            forks_count: r.forks_count,
            language: r.language,
            default_branch: r.default_branch,
            html_url: r.html_url,
        })
    }
}

export!(Component);
